/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adolfo_QboostService */

#ifndef _Included_com_adolfo_QboostService
#define _Included_com_adolfo_QboostService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adolfo_QboostService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adolfo_QboostService_init
  (JNIEnv *, jobject);

/*
 * Class:     com_adolfo_QboostService
 * Method:    setMode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_adolfo_QboostService_setMode
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_adolfo_QboostService
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adolfo_QboostService_uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
